sudo: required
services:
 - docker

before_install:
 - docker build -t phareesh76/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run phareesh76/react-test npm test -- --coverage

after_success:
 - docker build -t phareesh76/multi-client -f ./client
 - docker build -t phareesh76/multi-nginx -f ./nginx
 - docker build -t phareesh76/multi-server -f ./server
 - docker build -t phareesh76/multi-worker -f ./worker
 # Log in to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
 - docker push phareesh76/multi-client
 - docker push phareesh76/multi-nginx
 - docker push phareesh76/multi-server
 - docker push phareesh76/multi-worker
